### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by devnullnor** [mingaliu/DocumentDBStudio#18]
This tool doesn't seem to support UTF.

**Comment by mingaliu** [comment]
Can you explain in more details?  You mean the JSON editor doesn't support UTF?

**Comment by devnullnor** [comment]
Been a while since I used it, but yes, I think I had problems with UTF chars in the JSON editor.

**Comment by petertirrell** [comment]
I've come across this same thing.  I've been testing this specifically with non-English characters.  

The JSON display doesn't appear to render UTF8 characters correctly.  More specifically, the native IE renderer I think is what is not displaying characters correctly.  When a response is created (e.g, from a query), it goes through the PrettyPrintJson method and writes an html file with the results out to something like `C:\Users\myusername\AppData\Local\DocumentDBStudio\prettyPrint.Html`.  Then it just displays this file inline like 

```
// now launch it in broswer!
this.webBrowserResponse.Url = new Uri(prettyPrintHtml);
```

If you open this file in Chrome, UTF characters display just fine.  But at least on IE11 (Windows 10), the do not render how they should.  You can open the file directly with IE and see the same results as you get inside DocumentDB Studio.

**Comment by mingaliu** [comment]
Thanks, Peter!  I have merged your PR into main.
