### ISSUE TITLE
Downloaded solution does not build

### ISSUE THREAD

**Issue by MichaelReedOnly** [mingaliu/DocumentDBStudio#51]
Using VS-2015 (Enterprise).   
#1 Restoring NuGet on Build, fails.
#2  All references cannot be found, e.g. System, System.net.  
< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.1  (CLR:4.0)

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Azure.DocumentDB.1.10.0\build\Microsoft.Azure.DocumentDB.targets.	DocumentDBStudio	C:\temp\DocumentDBStudio-master\DocumentDBStudio-master\DocumentDBStudio\DocumentDBStudio.csproj	315	

Any help appreciated,
Michael

**Comment by prashantkhandelwal** [comment]
I am also facing the same issue when building the project with Visual Studio 2017 Enterprise. 

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Azure.DocumentDB.1.10.0\build\Microsoft.Azure.DocumentDB.targets.	DocumentDBStudio	C:\Github Code\DocumentDBStudio\DocumentDBStudio\DocumentDBStudio.csproj	315	

NuGet package restore is enabled but still it is showing me this error. I also tried clearing the package cache but it didn't work either.

**Comment by bojordan** [comment]
Replace all mentions of Microsoft.Azure.DocumentDB.1.10.0 with Microsoft.Azure.DocumentDB.1.11.1 in the .csproj file to unblock your build.

**Comment by MichaelReedOnly** [comment]
Worked like a charm !  Thanks, bojodan !
